---
- name: Clone the Git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    update: yes
  register: git_clone
  notify: Restart Flask Application
  tags:
    - clone_repo

- name: Ensure python3.12-venv is installed
  apt:
    name: python3.12-venv
    state: present
    update_cache: yes
  become: yes

- name: Recreate virtual environment (force clean setup)
  ansible.builtin.shell: rm -rf {{ venv_path }} && python3 -m venv {{ venv_path }}

- name: Ensure pip is installed in the virtualenv
  command: "{{ venv_path }}/bin/python -m ensurepip --upgrade"
  args:
    creates: "{{ venv_path }}/bin/pip"

- name: Install requirements in virtualenv
  command: "{{ venv_path }}/bin/pip install -r {{ requirements_file }}"
  environment:
    PATH: "{{ venv_path }}/bin:{{ ansible_env.PATH }}"

- name: Start the Flask application
  shell: nohup {{ venv_path }}/bin/python "{{ app_path }}" > /dev/null 2>&1 &
  tags:
    - start_app
