---
- name: Clone the Git repository
  git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    update: yes
  register: git_clone
  notify: Restart Flask Application
  tags:
    - clone_repo

- name: Create a virtual environment
  ansible.builtin.command: python3 -m venv /home/ubuntu/venv
  args:
    creates: /home/ubuntu/venv

- name: Install requirements in virtualenv
  ansible.builtin.command: /home/ubuntu/venv/bin/pip install -r /home/ubuntu/application/req.txt
  environment:
    PATH: "/home/ubuntu/venv/bin:{{ ansible_env.PATH }}"
  tags:
    - install_requirements

- name: Start the Flask application
  shell: nohup /home/ubuntu/venv/bin/python "{{ app_path }}" > /dev/null 2>&1 &
  tags:
    - start_app
